language: node_js
sudo: no
dist: trusty
node_js:
  - "7"
env:
  - CXX=g++-6 MONGODB=127.0.0.1 REDIS=127.0.0.1
install:
  - npm install -g npm@latest
  - npm cache clean
  - npm install --dev
  - npm install mocha
  - npm install coveralls
  - npm install istanbul
services:
  - mongodb
  - redis-server
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - r-packages-trusty
      - mongodb-3.0-precise
    packages:
      - g++-6
      - mongodb-org
script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
