language: node_js
sudo: no
dist: trusty
group: edge
node_js:
  - "8"
  - "9"
env:
  - CXX=g++-6 MONGODB=127.0.0.1 REDIS=127.0.0.1 ES=127.0.0.1:9200
install:
  - npm install -g npm@latest
  - npm install
  - npm install coveralls
  - npm install istanbul
services:
  - mongodb
  - redis-server
  - elasticsearch
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - r-packages-trusty
      - mongodb-3.0-precise
      - elasticsearch-5.x
    packages:
      - g++-6
      - mongodb-org
      - elasticsearch
script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
