language: node_js
sudo: no
node_js:
  - "7"
env:
  - CXX=g++-4.8
install:
  - npm install -g npm@latest
  - npm cache clean
  - npm install --dev
  - npm install mocha
  - npm install coveralls
  - npm install istanbul
services:
  - mongodb
  - redis-server
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
